- name: Install and start Nginx on Amazon Linux 2
  hosts: web
  become: yes
  tasks:
    - name: enable nginx from amazon-linux-extras
      command: amazon-linux-extras enable nginx1

    - name: install nginx
      yum:
        name: nginx
        state: present

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes

