name: Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Set up private key
      run: |
        echo "${{ secrets.PRIVATE_KEY }}" > /home/yktmg/Desktop/self_study_key.pem
        chmod 600 /home/yktmg/Desktop/self_study_key.pem

    - name: Run Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: |
        ansible-playbook -i inventory nginx.yml

